-- =====================================================================
-- Kütüphane v6 — shelves are no longer capped at six fixed slots.
--
-- v5 (library_shelves_v5.sql) seeded exactly six rows (ids 1-6) and
-- pinned that range with a check constraint, so the admin could only
-- rename/restock the six existing shelves. This drops the cap: id
-- becomes an auto-generated identity column so new shelves can be added
-- the same way articles get added (admin.html "+ Add Shelf"), and
-- existing shelves can be deleted when no longer wanted. Shelves that
-- already exist, and their articles, are untouched -- a shelf is
-- permanent once created, this migration just removes the fixed-count
-- ceiling that used to gate creating a new one.
--
-- Run in Supabase SQL editor. Idempotent.
-- =====================================================================

alter table public.library_shelves drop constraint if exists library_shelves_id_check;

-- Let Postgres generate ids for new rows, continuing after the highest
-- id already in use (1-6 from the v5 seed, or wherever things landed).
do $$
begin
  if not exists (
    select 1 from pg_attribute
    where attrelid = 'public.library_shelves'::regclass
      and attname = 'id'
      and attidentity <> ''
  ) then
    alter table public.library_shelves alter column id add generated by default as identity;
  end if;
end $$;

select setval(
  pg_get_serial_sequence('public.library_shelves', 'id'),
  coalesce((select max(id) from public.library_shelves), 0) + 1,
  false
);
